# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c2045ddd-91b1-4751-a7ef-c453c33a928f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-c2045ddd-91b1-4751-a7ef-c453c33a928f".device = "/dev/disk/by-uuid/c2045ddd-91b1-4751-a7ef-c453c33a928f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/51BD-899F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f4169635-35a5-4765-8a6b-c3bf07bc0791"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
